install: gradle wrapper --gradle-version 4.10
language: java
# use Java 8
jdk:
- oraclejdk8

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.8-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

before_script:
  - mysql -e 'create database usersdemo;'

# cache the build tool's caches
cache:
 directories:
 - $HOME/.m2
 - $HOME/.gradle